version = 0.1

[dev.deploy.parameters]
stack_name = "alpaca-alerts-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
resolve_image_repos = true
resolve_s3 = true
image_repositories = []
parameter_overrides = "Env=dev NtfyAlertsTopic=alpaca-alerts-wyEb7SuBXRcM ManageCron=\"cron(* 13-20 ? * MON-FRI *)\""
confirm_changeset = false

[prod.deploy.parameters]
stack_name = "alpaca-alerts-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
resolve_image_repos = true
resolve_s3 = true
image_repositories = []
parameter_overrides = "Env=prod NtfyAlertsTopic=alpaca-alerts-IfIuknyToSNN ScheduleState=DISABLED ManageCron=\"cron(* 13-20 ? * MON-FRI *)\""
confirm_changeset = false
